### ISSUE TITLE
[feat] 메인 페이지 UI

### ISSUE THREAD

**Issue by rlotr02** [Nook-Book/Client#1]
## 🌏 Summary

>  메인 페이지 UI

## ✔️ Task & Description

- [x] 메인 페이지 UI
- [x] 알림 페이지 UI
- [x] 온보딩 화면 UI
- [x] 리스트 편집 화면 UI
- [x] 리스트 편집 화면 컬렉션 추가
- [x] 리스트 편집 화면 편집 완료 모달창
- [x] 최대 지정 가능한 컬렉션 수 경고 모달창
- [x] Header/Main
- [x] Header/Search/ButtonBox/Header/Edit

## 🐸 Reference
- [StackScreen](https://reactnavigation.org/docs/tab-based-navigation)
