### ISSUE TITLE
[feat] 도서 상세 페이지 UI

### ISSUE THREAD

**Issue by rlotr02** [Nook-Book/Client#12]
## 🌏 Summary

>  도서 상세 페이지 UI

## ✔️ Task & Description

- [x] 도서 상세 페이지 UI
- [x] 도서 상세 페이지 공유 리스트
- [x] 컬렉션 선택 리스트
- [x] 컬렉션 추가 모달창
- [x] 컬렉션 선택 UI 수정
- [x] 컬렉션 저장 시 애니메이션 추가
- [ ] 독서 글쓰기 노트 UI
- [x] 카메라, 사진첩 사진 불러오기
- [x] 기록 보기 페이지 UI
- [x] 타이머 페이지 UI
