### ISSUE TITLE
[feat] 챌린지 페이지 UI

### ISSUE THREAD

**Issue by rlotr02** [Nook-Book/Client#13]
## 🌏 Summary

>  챌린지 페이지 UI

## ✔️ Task & Description

- [x] 챌린지 페이지 UI
- [x] 챌린지 전체보기 페이지
- [x] 초대된 챌린지 상세보기 페이지
- [x] 챌린지 생성 페이지
- [x] 캘린더 UI
- [x] 친구 선택 페이지
- [x] 챌린지 상세보기 페이지
- [x] 현황 카드 모달창
- [x] 현황 카드 상세보기 페이지
- [x] 챌린지 설정 페이지
- [x] 챌린지 삭제 모달창
- [x] 챌린지 참여자 관리 페이지
- [x] 챌린지 참여자 삭제 모달창
- [x] 챌린지 참여자 추가 페이지
- [x] 챌린지 수정 페이지
