### ISSUE TITLE
[feat] 마이 페이지 

### ISSUE THREAD

**Issue by si14444** [Nook-Book/Client#19]
## 🌏 Summary

>  마이페이지 ui 구현

## ✔️ Task & Description

- [x] 마이 페이지 ui
- [ ] 마이 페이지 - 설정 페이지 ui
- [ ] 모달
- [ ] 프로필 편집
- [ ] 프로필 사진 선택
- [ ] 친구 페이지 ui
- [ ] 컬렉션 전체보기 ui
- [ ] 마이페이지 기록 전체보기 ui

## 🐸 Reference

-
