### ISSUE TITLE
[design] 컬러 시스템, 폰트 시스템 추가

### ISSUE THREAD

**Issue by rlotr02** [Nook-Book/Client#2]
## 🌏 Summary

>  컬러 시스템, 폰트 시스템 추가

## ✔️ Task & Description

- [x] 컬러 시스템 추가
- [x] 폰트 시스템 추가
- [x] 아이콘 추가
- [x] 네비게이션바 svg 수정
- [x] 네비게이션바 UI 수정

## 🐸 Reference

- [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer?tab=readme-ov-file)
- [svg-currentColor](https://velog.io/@party3205/React-Native-SVG)
