### ISSUE TITLE
[feat] 검색 페이지 UI

### ISSUE THREAD

**Issue by si14444** [Nook-Book/Client#3]
## 🌏 Summary

>검색 페이지 UI  

## ✔️ Task & Description

- [x] 검색 메인 페이지 ui
- [x] 검색 input 입력 시 키보드 노출
- [x] 최근 검색어 노출
- [x] 검색 결과 페이지 ui

## 🐸 Reference

-
